# Site settings
title: willyschultz.com
email: wschultz@williamjdesign.com
description: My name is Willy Schultz and this is my website where you can find my projects and ideas. I am currently working as a software engineer on the Distributed Systems team at MongoDB.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willyschultz.com" # the base hostname & protocol for your site
twitter_username: willyjschultz
github_username:  will62794

# Build settings
markdown: kramdown
collections:
  projects:
    output: true
  posts:
plugins:
  - jekyll-sitemap
