# Site settings
title: willyschultz.com
email: wschultz@williamjdesign.com
description: My name is Willy Schultz and this is my website where you can find my projects and ideas. I am a programmer, designer, and builder. I am currently studying Mathematics at Cornell University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willyschultz.com" # the base hostname & protocol for your site
twitter_username: willyjschultz
github_username:  will62794

# Build settings
markdown: kramdown
collections:
  projects:
    output: true
  posts:
gems:
  - jekyll-sitemap
