# Site settings
title: Will Schultz
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  will62794

# Build settings
markdown: kramdown
theme: minima
collections:
  projects:
    output: true
  posts:
      #plugins:
      #  - jekyll-sitemap
