# Site settings
title: William Schultz
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://will62794.github.io" # the base hostname & protocol for your site
github_username:  will62794
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: minima
collections:
  projects:
    output: true
  posts:

